### ISSUE TITLE
CLI version

### ISSUE THREAD

**Issue by garettwinkler** [ERG-Capstone/EmergencyResponseGuide#2]
![image](https://cloud.githubusercontent.com/assets/7133552/18501415/200ed09e-7a05-11e6-8248-90f1ccbec02d.png)

Alert shown when launching app preview on Android.

**Comment by garettwinkler** [comment]
This might be the fix.

https://software.intel.com/en-us/forums/intel-xdk/topic/606371

Instruction to update CLI version: Intel XDK -> Projects tab -> Build Settings -> Cordova CLI Version (pencil icon = Change Cordova version)

**Comment by spencerbyw** [comment]
Did this cause any changes to the xdk stuff? If so can you push that code?

**Comment by spencerbyw** [comment]
Fixed here https://github.com/ERG-Capstone/EmergencyResponseGuide/commit/9e2a12a9eaa3e8bb5941856566d586b55ac963a8#commitcomment-19030488
